### ISSUE TITLE
After starting, only CPU is displayed.

### ISSUE THREAD

**Issue by enusr2k** [RadAd/RadMeter#1]
Hi! I can't get the result like in the screenshot.

![RadMeter](https://user-images.githubusercontent.com/115537081/218539451-e227744f-e9ec-4081-9f67-de96a3bd12ce.png)

After starting, only CPU is displayed.

_RadMeter.cpp_ contains 

> { _T("Memory"),    _T("\\Memory\\Available Bytes"),                    _T("B"), PDH_FMT_DOUBLE, RGB(139, 18, 174),  {}, G(16.0) },
{ _T("Disk"),      _T("\\PhysicalDisk(_Total)\\% Disk Time"),          _T(""),  PDH_FMT_DOUBLE, RGB(77, 166, 12) },
{ _T("Net D"),     _T("\\Network Interface(*)\\Bytes Received/sec"),   _T("B"), PDH_FMT_DOUBLE, RGB(167, 79, 1),    {}, 2000, true },
 { _T("Net U"),     _T("\\Network Interface(*)\\Bytes Sent/sec"),       _T("B"), PDH_FMT_DOUBLE, RGB(237, 165, 130), {}, 2000, true },
{ _T("GPU"),       _T("\\GPU Engine(*)\\Utilization Percentage"),      _T(""),  PDH_FMT_DOUBLE, RGB(172, 57, 49) },

But how can they be used?

**Comment by RadAd** [comment]
It should appear something like the screenshot by default.

It can be customised by editing the registry.

There isnt any document for it but here is mine:
```Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter]
"FontFace"="Segoe UI"
"FontSize"=dword:00000008
"Margin"=dword:00000005
"x"="cxscreen - width"
"y"="cyscreen / 4"

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters]
"Order"=hex(7):43,00,50,00,55,00,00,00,50,00,72,00,6f,00,63,00,65,00,73,00,73,\
  00,65,00,73,00,00,00,4d,00,65,00,6d,00,6f,00,72,00,79,00,00,00,44,00,69,00,\
  73,00,6b,00,00,00,4e,00,65,00,74,00,44,00,6f,00,77,00,6e,00,00,00,4e,00,65,\
  00,74,00,55,00,70,00,00,00,47,00,50,00,55,00,00,00,00,00
"Width"=dword:00000050
"Height"=dword:00000028

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\CPU]
"Counter"="\\Processor(_Total)\\% Processor Time"
"Color"=dword:00bb7d11
"Format"="double"

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\Disk]
"Counter"="\\PhysicalDisk(_Total)\\% Disk Time"
"Color"=dword:000ca64d

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\GPU]
"Counter"="\\GPU Engine(*)\\Utilization Percentage"
"Color"=dword:003139ac

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\Memory]
"Counter"="\\Memory\\Available Bytes"
"Color"=dword:00ae128b
"Unit"="B"
"Max"=hex(b):00,00,00,00,04,00,00,00

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\NetDown]
"Counter"="\\Network Interface(*)\\Bytes Received/sec"
"Color"=dword:00014fa7
"Unit"="B"
"Max"=dword:000007d0
"AutoScale"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\NetUp]
"Counter"="\\Network Interface(*)\\Bytes Sent/sec"
"Color"=dword:0082a5ed
"Unit"="B"
"Max"=dword:000007d0
"AutoScale"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\RadSoft\RadMeter\Meters\Processes]
"Counter"="\\System\\Processes"
"Color"=dword:00cfa458
"Format"="long"
"Max"=dword:000001f4

```

**Comment by enusr2k** [comment]
It worked! Thank you so much!
The tool is awesome!
May I also ask if there is a key to not display on top of all windows?

(BTW, by default the utility did not create keys in the registry. I don't know why).
Upd: Maybe it's because I'm using a non-English Windows. In this case, Windows displays the names of the counters in a non-English language.
![2023-02-14_122741](https://user-images.githubusercontent.com/115537081/218668600-3775159b-2143-4b12-9c01-77ec2f6640e7.png)

**Comment by RadAd** [comment]
Glad it worked.

There is currently no key to stop the display on top of all windows.

I haven't fully finalised the behaviour when mousing over either.

The utility doesn't create any registry entries. It should have had a default list of meters when there is nothing in the registry but it looks like I have commented that out.

I haven't tried it on non-English Windows. The code uses `PdhAddEnglishCounter` so the registry entries should be English on all versions of Windows.
